version: '3.9'

services:
  mongodb:
    image: mongo:8.0
    container_name: learnwithabran-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
